version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-northeast-2:860061945305:task-definition/process-pension-td:7"
        LoadBalancerInfo:
          ContainerName: "process-pension-c"
          ContainerPort: "8011"
        PlatformVersion: "LATEST"